### ISSUE TITLE
nvidia/digits doesn't run

### ISSUE THREAD

**Issue by cimenx** [NVIDIA/nvidia-docker#122]
Hi, i'm trying to use docker version of nvidia digits 4 but when i execute
`nvidia-docker run --name digits-gpu -v /home/wildan/Data:/data -P nvidia/digits`
it has this error
```
2016-06-24 07:44:11 [8] [INFO] Starting gunicorn 17.5
libdc1394 error: Failed to initialize libdc1394
2016-06-24 07:44:12 [8] [DEBUG] Arbiter booted
2016-06-24 07:44:12 [8] [INFO] Listening at: http://0.0.0.0:34448 (8)
2016-06-24 07:44:12 [8] [INFO] Using worker: socketio.sgunicorn.GeventSocketIOWorker
2016-06-24 07:44:12 [54] [INFO] Booting worker with pid: 54
2016-06-24 07:44:12 [54] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 472, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "gunicorn_config.py", line 12, in post_fork
    from digits.webapp import scheduler
  File "/opt/digits/digits/webapp.py", line 54, in <module>
    import digits.model.images.classification.views
  File "/opt/digits/digits/model/images/classification/views.py", line 13, in <module>
    from .forms import ImageClassificationModelForm
  File "/opt/digits/digits/model/images/classification/forms.py", line 7, in <module>
    from ..forms import ImageModelForm
  File "/opt/digits/digits/model/images/forms.py", line 7, in <module>
    from ..forms import ModelForm
  File "/opt/digits/digits/model/forms.py", line 17, in <module>
    class ModelForm(Form):
  File "/opt/digits/digits/model/forms.py", line 293, in ModelForm
    ) for index in config_value('gpu_list').split(',') if index],
  File "/opt/digits/digits/device_query.py", line 233, in get_nvml_info
    raise RuntimeError('nvmlDeviceGetHandleByIndex() failed with error #%s' % rc)
RuntimeError: nvmlDeviceGetHandleByIndex() failed with error #2
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 472, in spawn_worker
    self.cfg.post_fork(self, worker)
  File "gunicorn_config.py", line 12, in post_fork
    from digits.webapp import scheduler
  File "/opt/digits/digits/webapp.py", line 54, in <module>
    import digits.model.images.classification.views
  File "/opt/digits/digits/model/images/classification/views.py", line 13, in <module>
    from .forms import ImageClassificationModelForm
  File "/opt/digits/digits/model/images/classification/forms.py", line 7, in <module>
    from ..forms import ImageModelForm
  File "/opt/digits/digits/model/images/forms.py", line 7, in <module>
    from ..forms import ModelForm
  File "/opt/digits/digits/model/forms.py", line 17, in <module>
    class ModelForm(Form):
  File "/opt/digits/digits/model/forms.py", line 293, in ModelForm
    ) for index in config_value('gpu_list').split(',') if index],
  File "/opt/digits/digits/device_query.py", line 233, in get_nvml_info
    raise RuntimeError('nvmlDeviceGetHandleByIndex() failed with error #%s' % rc)
RuntimeError: nvmlDeviceGetHandleByIndex() failed with error #2
2016-06-24 07:44:12 [54] [INFO] Worker exiting (pid: 54)

Error: nvmlDeviceGetHandleByIndex() failed with error #2
```
my gpu information
```
+------------------------------------------------------+                       
| NVIDIA-SMI 367.18     Driver Version: 367.18         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 740M     Off  | 0000:01:00.0     N/A |                  N/A |
| N/A   48C    P0    N/A /  N/A |    546MiB /  2003MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```

**Comment by 3XX0** [comment]
Probably a bug in digits, ping @lukeyeager 
The function failing is actually `nvmlDeviceGetHandleByPciBusId`, the error message is wrong.
It's missing the soname [here](https://github.com/NVIDIA/DIGITS/commit/183457ac63cd1bf52e7ec897c137883450419eab#diff-3b92095004998be34185e59f5e3f8413R101), this could be the root cause.

**Comment by flx42** [comment]
It works fine on all the machine I tested.
Error 2 seems to be invalid argument:
```
    NVML_ERROR_INVALID_ARGUMENT = 2,    //!< A supplied argument is invalid  
```
Either your `nvidia_driver` volume is bogus, or there is a problem when querying this particular GPU.

**Comment by flx42** [comment]
@3XX0 you're looking at old code:
https://github.com/NVIDIA/DIGITS/blob/9de2392a4c02ffa254ba8fd391329dcd919cf6e6/digits/device_query.py#L141-L155

**Comment by 3XX0** [comment]
@cimenx are you using `NV_GPU`?

**Comment by cimenx** [comment]
@3XX0  yes, i'm using `NV_GPU=0`
@flx42 how do i check if my `nvidia_driver` volume is bogus ?

**Comment by 3XX0** [comment]
Can you try with this environment variable: `export CUDA_​DEVICE_​ORDER=PCI_BUS_ID`

**Comment by 3XX0** [comment]
Any update?

**Comment by cimenx** [comment]
previously i using nvidia-docker rc3 but it give me error `error == cudaSuccess (30 vs. 0)`
then i build it from source this day and it fix now. I can run digits 4 on docker now :)

**Comment by flx42** [comment]
Did you compile `nvidia-docker` (the plugin) from source? Or did you create the images from source? (from the Dockerfiles).

**Comment by cimenx** [comment]
Yes, `nvidia-docker` from source. I'm not creating docker images and compile it there.
