### ISSUE TITLE
Tensorflow fails with cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE

### ISSUE THREAD

**Issue by streamnsight** [NVIDIA/nvidia-docker#262]
running tensorflow with 
`sudo nvidia-docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow:latest-gpu`

and when openign a tf.Session() I get:

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-45-generic/modules.dep.bin'
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: b73324416bd2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: b73324416bd2
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 367.48.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.48  Sat Sep  3 18:21:08 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.48.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 367.48.0
```

I have a GTX460 and GTX780 Ti on the machine, running Ubuntu 16.04 LTS

How should I go about debugging this?

Thanks

**Comment by 3XX0** [comment]
Your driver is in a weird state, or `nvidia-docker` couldn't initialize the driver.
Executing `sudo nvidia-modprobe -u -c=0` on the host shoud fix it.

**Comment by streamnsight** [comment]
@3XX0 
Merci Jonathan 

Looking through the logs, I saw that there was some driver mismatch

a 361 driver was installed, but nvidia-docker-plugin seems to be looking for 367.
On boot, nvidia-docker-plugin would not start and listed the mismatch in logs
I upgraded to 367, and could start nvidia-docker-plugin, but when I ran 

```
sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
```
I got:
```
docker: Error response from daemon: create nvidia_driver_367.57: create nvidia_driver_367.57: Error looking up volume plugin nvidia-docker: Post http://%2Fvar%2Flib%2Fnvidia-docker%2Fnvidia-docker.sock/Plugin.Activate: dial unix /var/lib/nvidia-docker/nvidia-docker.sock: connect: no such file or directory.
See 'docker run --help'.
```

I had to reinstall nvidia-docker again after that to make it work.

but now it seem to work

**Comment by streamnsight** [comment]
one more question though (related to Tensor Flow image, so I'm not sure you can answer)

when I run the image once, it works fine. I shut it down while a notebook was open, and when I run again I get:

```
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x43be9a0
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
[```

So it seems like the context is still active even after shutting down the docker container.
Is that something TensorFlow is supposed to clean up on exit, or is it supposed to be handled by docker / nvidia-docker?

Thanks

**Comment by streamnsight** [comment]
Actually... my bad: it seems to be doing this the first time I create a TensorFlow session, but after re-running the code, it runs... I'll have to dig a bit more here.

**Comment by 3XX0** [comment]
Try the tensorflow image from the [DockerHUB](https://hub.docker.com/r/tensorflow/tensorflow/) instead

**Comment by streamnsight** [comment]
tried the DockerHub image but no change:
creating the TF session always seems to fail the first time, but works afterwards.
Is this something in your court, or should I report with the TF project?

Thanks

**Comment by 3XX0** [comment]
How many GPUs do you have?
This might be a Tensorflow issue, can you paste de full initialization of `python -m tensorflow.models.image.mnist.convolutional`

**Comment by streamnsight** [comment]
```
# python -m tensorflow.models.image.mnist.convolutional                                                                          
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally                              
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally                               
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally                               
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally                              
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally                              
Extracting data/train-images-idx3-ubyte.gz                                                                                         
Extracting data/train-labels-idx1-ubyte.gz                                                                                         
Extracting data/t10k-images-idx3-ubyte.gz                                                                                          
Extracting data/t10k-labels-idx1-ubyte.gz                                                                                          
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:                                            
name: GeForce GTX 780 Ti                                                                                                           
major: 3 minor: 5 memoryClockRate (GHz) 1.0715                                                                                     
pciBusID 0000:83:00.0                                                                                                              
Total memory: 2.95GiB                                                                                                              
Free memory: 2.88GiB                                                                                                               
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x2b162c0           
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Int
ernal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE                                                          
Traceback (most recent call last):                                                                                                 
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main                                                             
    "__main__", fname, loader, pkg_name)                                                                                           
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code                                                                        
    exec code in run_globals                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 339, in <module>              
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)                                                                           
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run                                 
    sys.exit(main(sys.argv[:1] + flags_passthrough))                                                                               
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 284, in main                  
    with tf.Session() as sess:                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1186, in __init__                        
    super(Session, self).__init__(target, graph, config=config)                                                                    
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 551, in __init__                         
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)                                                               
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__                                                                    
    self.gen.next()                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_
status                                                                                                                             
    pywrap_tensorflow.TF_GetCode(status))                                                                                          
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.         
```

In the JuPyter notepad, if I run the bloc that creates the session a second time, it goes on fine.
Somehow it fails creating the session the first time.

**Comment by flx42** [comment]
What's the output of `nvidia-smi` outside of Docker?

**Comment by streamnsight** [comment]
nvidia French connection a la rescousse... awesome! (ps: we met at the k8s meetup)

so, here is what i got:

```
$ nvidia-smi
Wed Dec  7 22:30:29 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 460     Off  | 0000:03:00.0     N/A |                  N/A |
| 40%   39C    P0    N/A /  N/A |    107MiB /  1984MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 780 Ti  Off  | 0000:83:00.0     N/A |                  N/A |
| 34%   31C    P8    N/A /  N/A |     29MiB /  3020MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+
```
Does this help?

**Comment by streamnsight** [comment]
The full JuPyter log to the session open
```
$ sudo nvidia-docker run -it -p 8888:8888 -e CUDA_VISIBLE_DEVICES=0 tensorflow/tensorflow:latest-gpu
[I 06:40:38.689 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 06:40:38.705 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 06:40:38.706 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 06:40:38.726 NotebookApp] Serving notebooks from local directory: /notebooks
[I 06:40:38.726 NotebookApp] 0 active kernels 
[I 06:40:38.726 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 06:40:38.727 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).


[W 06:40:45.818 NotebookApp] 404 GET /api/kernels/c839e9ba-7866-45d8-95d3-59c5e48f36e4/channels?session_id=923C793918DD4E0A8FEDB9BC411B8727 (192.168.10.38): Kernel does not exist: c839e9ba-7866-45d8-95d3-59c5e48f36e4
[W 06:40:45.861 NotebookApp] 404 GET /api/kernels/c839e9ba-7866-45d8-95d3-59c5e48f36e4/channels?session_id=923C793918DD4E0A8FEDB9BC411B8727 (192.168.10.38) 51.31ms referer=None
[I 06:40:51.056 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 06:40:51.074 NotebookApp] Notebook 3_mnist_from_scratch.ipynb is not trusted
[W 06:40:51.135 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161208064038 (192.168.10.38) 2.67ms referer=http://192.168.10.40:8888/notebooks/3_mnist_from_scratch.ipynb
[I 06:40:52.304 NotebookApp] Kernel started: 0a5b8d6a-2b0f-4ee7-8c0b-f49500ebbe54
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 780 Ti
major: 3 minor: 5 memoryClockRate (GHz) 1.0715
pciBusID 0000:83:00.0
Total memory: 2.95GiB
Free memory: 2.85GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:83:00.0)
```

**Comment by flx42** [comment]
You mean the **Docker** french connection ;)

TensorFlow chokes on your 460 (Fermi) GPU, it looks like `cuDevicePrimaryCtxRetain` is not supported on this arch. Which seems to be confirmed [here](https://github.com/tensorflow/tensorflow/blob/d9a89a5cf63b2ecedf68d3eefdc24be3f519e503/tensorflow/stream_executor/cuda/cuda_driver.cc#L605-L610).
In your last example you use `CUDA_VISIBLE_DEVICES` to ignore your 460 GPU so it works fine, but if you don't set this variable, does it still work after the first try session?!

By the way, you can also use `NV_GPU=1 nvidia-docker run ...` to isolate devices (using the `nvidia-smi` ordering)

**Comment by flx42** [comment]
Thinking about it, there is no obvious reason why `cuDevicePrimaryCtxRetain` would not work on older archs if your code was compiled with a recent CUDA toolkit, I can try to dig more information.

**Comment by streamnsight** [comment]
OK...
so it's when i don't pass a CUDA_VISIBLE_DEVICES flag that it fails the first time
```
$ sudo nvidia-docker run -it -p 8888:8888 tensorflow/tensorflow:latest-gpu
[I 06:58:34.455 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[W 06:58:34.471 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 06:58:34.471 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 06:58:34.492 NotebookApp] Serving notebooks from local directory: /notebooks
[I 06:58:34.492 NotebookApp] 0 active kernels 
[I 06:58:34.492 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 06:58:34.492 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 06:58:37.002 NotebookApp] 404 GET /api/kernels/74c2f6de-a2b4-4aec-a1e2-1f80d03be8c4/channels?session_id=FD341927D1F6451C9FE6DDD57685DE2F (192.168.10.38): Kernel does not exist: 74c2f6de-a2b4-4aec-a1e2-1f80d03be8c4
[W 06:58:37.044 NotebookApp] 404 GET /api/kernels/74c2f6de-a2b4-4aec-a1e2-1f80d03be8c4/channels?session_id=FD341927D1F6451C9FE6DDD57685DE2F (192.168.10.38) 50.14ms referer=None
[I 06:58:38.349 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 06:58:38.365 NotebookApp] Notebook 3_mnist_from_scratch.ipynb is not trusted
[W 06:58:38.429 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161208065834 (192.168.10.38) 2.84ms referer=http://192.168.10.40:8888/notebooks/3_mnist_from_scratch.ipynb
[I 06:58:39.381 NotebookApp] Kernel started: c7f73947-3f3d-43ef-9e4e-b1adca8cefe4
[W 06:58:45.997 NotebookApp] Replacing stale connection: 74c2f6de-a2b4-4aec-a1e2-1f80d03be8c4:FD341927D1F6451C9FE6DDD57685DE2F
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 780 Ti
major: 3 minor: 5 memoryClockRate (GHz) 1.0715
pciBusID 0000:83:00.0
Total memory: 2.95GiB
Free memory: 2.85GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x77b75c0
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
[I 06:59:12.042 NotebookApp] Saving file at /3_mnist_from_scratch.ipynb
[W 06:59:12.045 NotebookApp] Saving untrusted notebook 3_mnist_from_scratch.ipynb
```

Maybe it's trying the 1st device (device 0) and gives up, even though it says it found the other one (the GTX 780 Ti).
it seems like the flag is key here to make it work.

**Comment by flx42** [comment]
If you run without the flag, it **always** fail, right?
TensorFlow is greedy, it will use all the devices you throw at it.

**Comment by streamnsight** [comment]
yes, always fails **the first time**, but works the second time i run the session start block

here is the log:

```
sudo nvidia-docker run -it -p 8888:8888 tensorflow/tensorflow:latest-gpu
...
referer=http://192.168.10.40:8888/notebooks/3_mnist_from_scratch.ipynb
[I 07:08:56.793 NotebookApp] Kernel started: 65df2bb5-924f-491f-b742-8cb3c844b1a2
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 780 Ti
major: 3 minor: 5 memoryClockRate (GHz) 1.0715
pciBusID 0000:83:00.0
Total memory: 2.95GiB
Free memory: 2.85GiB
---> first try running the tf.InteractiveSession() block
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x7728330
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE
---> second try running the tf.InteractiveSession() block
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x7728330
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 780 Ti, pci bus id: 0000:83:00.0)
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x7728330
```

**Comment by flx42** [comment]
Oh ok, so TensorFlow errors out during initialization but actually excludes that device **for the next use**, that's a bit weird but not our fault :)

**Comment by 3XX0** [comment]
Yeah probably the Fermi failing, `CUDA device ordinal 1` is the GTX 460 with the CUDA ordering.
Try isolating the cards `sudo NV_GPU=1 nvidia-docker run -it -p 8888:8888 tensorflow/tensorflow:latest-gpu` should work and sudo NV_GPU=0 nvidia-docker run -it -p 8888:8888 tensorflow/tensorflow:latest-gpu` should fail everytime

**Comment by streamnsight** [comment]
ok. great, thanks
any reason CUDA_VISIBLE_DEVICES=0 works and CUDA_VISIBLE_DEVICES=1 doesn't? 
i.e. any reason the ordering is different with that flag?

**Comment by 3XX0** [comment]
Yeah `CUDA_VISIBLE_DEVICES=0` is the fastest GPU by default namely the GTX 780 Ti and `1` will be the Fermi hence the failure

**Comment by streamnsight** [comment]
with CUDA_VISIBLE_DEVICES=1
I get:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 460
major: 2 minor: 1 memoryClockRate (GHz) 1.4
pciBusID 0000:03:00.0
Total memory: 1.94GiB
Free memory: 1.74GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: GeForce GTX 460, pci bus id: 0000:03:00.0) with Cuda compute capability 2.1. The minimum required Cuda capability is 3.0.
```

So it detects the device and finds it doesnt have the minimum caps.

**Comment by streamnsight** [comment]
@3XX0 so CUDA_VISIBLE_DEVICES doesn't match the nvidia-smi order?

**Comment by streamnsight** [comment]
that's confusing

**Comment by 3XX0** [comment]
Yeah I know...
See https://docs.nvidia.com/cuda/cuda-c-programming-guide/#env-vars

**Comment by streamnsight** [comment]
thanks.
anyways, I love this docker plugin and images. 
So much easier than installing all this stuff manually.
Great job!

**Comment by 3XX0** [comment]
In general prefer using `NV_GPU` rather than `CUDA_VISIBLE_DEVICES` when dealing with containers, it provides better isolation and respects the `nvidia-smi` order
