### ISSUE TITLE
/usr/local/nvidia/bin/nvidia-smi: No such file or directory

### ISSUE THREAD

**Issue by p2004r** [NVIDIA/nvidia-docker#287]
```
# nvidia-smi 
Mon Jan  9 20:44:50 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.20                 Driver Version: 375.20                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 460     Off  | 0000:01:00.0     N/A |                  N/A |
| 40%   34C    P8    N/A /  N/A |    457MiB /   993MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 460     Off  | 0000:02:00.0     N/A |                  N/A |
| 40%   31C   P12    N/A /  N/A |     74MiB /   993MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
+-----------------------------------------------------------------------------+

# nvidia-docker run --rm nvidia/cuda nvidia-smi
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x7ddca0, 0xc82012f180)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201092e8)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7ddca0, 0xc82012f180)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820108bf8, 0xc82001e040, 0xc820108d08)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc8200b2fa0, 0x7f56f98cb960, 0xc82012f180)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc8200c43c0, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x7446a0, 0x8f09d0, 0x13, 0x839798, 0x4, 0xc820109268, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7446a0, 0x8f09d0, 0x13, 0xc820109268, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x7446a0, 0x8f09d0, 0xc8200c43c0, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x83c628, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8cff80, 0x51, 0x0, ...)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001680, 0xc820070060, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
	/go/src/github.com/opencontainers/runc/main.go:137 +0xe24


# nvidia-docker run -ti --rm nvidia/cuda bash
root@111dd6aa4001:/# nvidia-smi 
bash: /usr/local/nvidia/bin/nvidia-smi: No such file or directory
root@111dd6aa4001:/# ls -la /usr/local/nvidia/bin/nvidia-smi
-rwxr-xr-x 2 root root 458680 Nov 16 01:40 /usr/local/nvidia/bin/nvidia-smi

'''

I can not understand how it happens :(

**Comment by YH-Wu** [comment]
Check this
https://github.com/NVIDIA/nvidia-docker/wiki/Installation

Prerequisites:
...
NVIDIA GPU with Architecture > Fermi (2.1)
...

GTX 460 is Compute 2.1
