### ISSUE TITLE
NVMLError_Unknown: Unknown Error while pushing NVIDIA GPU metrics to Prometheus

### ISSUE THREAD

**Issue by ajeetraina** [NVIDIA/nvidia-docker#455]
I am trying to integrate Prometheus to nvidia-docker daemon.Here is my system configuration:

Docker Version: 17.06
OS: Ubuntu 16.04 LTS
Environment : Manager Server Instance with GPU
GPU: GeForce GTX 1080 Graphics card

Installed CUDA driver with the following command:

```
$sudo dpkg -i cuda-repo-ubuntu1604_8.0.44-1_amd64.deb 
(Reading database ... 231957 files and directories currently installed.)
Preparing to unpack cuda-repo-ubuntu1604_8.0.44-1_amd64.deb ...
Unpacking cuda-repo-ubuntu1604 (8.0.44-1) over (8.0.44-1) ...
Setting up cuda-repo-ubuntu1604 (8.0.44-1) ...
OK

$export LD_LIBRARY_PATH=/usr/local/cuda/lib
$export PATH=$PATH:/usr/local/cuda/bin
$nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

# Verifying NVIDIA DOCKER CLI

```
ajit@Ubuntu-1604-xenial-64-minimal:~/test/nvidia-prometheus-stats$ curl -s localhost:3476/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_375.66:/usr/local/nvidia:ro --device=/dev/nvidiactl
 --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia0ajit@Ubuntu-1604-xenial-64
-minimal:~/test/nvidia-prometheus-stats$ which nvidia-docker-plugin 
/usr/local/bin/nvidia-docker-plugin
```
 
# Creating Prometheus Container:
```
$nvidia-docker run --name prometheus -d -p `hostname -i`:9090:9090
 quay.io/prometheus/prometheus
f0ef97418f92f54c645678a7837270657f4b6577ce2dde3bf9cac6335b542665
```

Output:
```
docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS 
             PORTS                         NAMES
f0ef97418f92        quay.io/prometheus/prometheus   "/bin/prometheus -..."   2 days ago          Up 2 da
ys           94.130.33.61:9090->9090/tcp   prometheus
```

I used https://github.com/BonsaiAI/nvidia-prometheus-stats repository which claims scraping Memory and GPU utilization metrics using NVML and exposes them to Prometheus through a simple HTTP server and/or a push gateway.

Used the below Dockerfile

```
FROM ubuntu:16.04
RUN apt-get update -y && \
    apt-get install -y wget git python python-pip python3-dev python-dev
RUN git clone https://github.com/BonsaiAI/nvidia-prometheus-stats
WORKDIR nvidia-prometheus-stats
RUN pip install nvidia-ml-py pyinstaller prometheus_client
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
RUN dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
RUN apt-get update -y
RUN apt-get install -y cuda
RUN pyinstaller nvidia-prometheus-stats.py 
```

Built the container and started it:

```
$git clone https://github.com/ajeetraina/nvidia-prometheus-stats
$cd nvidia-prometheus-stats
$docker build -t ajeetraina/nvidia-prometheus-stats . -f Dockerfile.ubuntu1604
```
Starting the container:

```
$nvidia-docker run -itd ajeetraina/nvidia-prometheus-stats  bash
```

```
sudo docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             ST
ATUS              PORTS                         NAMES
3b292ffdc3e3        ajeetraina/nvidia-prometheus-stats   "bash"                   3 seconds ago       Up
 2 seconds                                      gallant_booth
f0ef97418f92        quay.io/prometheus/prometheus        "/bin/prometheus -..."   2 days ago          Up
 2 days           94.130.33.61:9090->9090/tcp   prometheus
```

While I try to push GPU metrics to Prometheus, I encountered the below error:

```
 sudo docker exec -it 3b2 /nvidia-prom
etheus-stats/dist/nvidia-prometheus-stats/nvidia-prometheus-stats -g 94.130.33.61:9090 -p 8080
ERROR:nvidia-tool:Exception thrown - Unknown Error
Traceback (most recent call last):
  File "nvidia-prometheus-stats.py", line 86, in main
    nvmlInit()
  File "pynvml.py", line 754, in nvmlInit
  File "pynvml.py", line 405, in _nvmlCheckReturn
NVMLError_Unknown: Unknown Error
ajit@Ubuntu-1604-xenial-64-minimal:~/test/nvidia-prometheus-stats$
```

**Comment by 3XX0** [comment]
Your driver is probably not installed correctly, can you check that `nvidia-smi` works on the host?

**Comment by babacoders** [comment]
Got it fixed. Planning to come up with blog so that it will be helpful for the community. Thanks.

**Comment by ajeetraina** [comment]
Finally got it fixed. Planning to come up with blog post.
