### ISSUE TITLE
Theano Support in nvidia-docker v2

### ISSUE THREAD

**Issue by marco-lavagnino** [NVIDIA/nvidia-docker#601]
### 1. Issue or feature description

Using Theano from python code works as expected on nvidia-docker version 1, but fails in version 2 with the following traceback:
```
docker run --runtime=nvidia --rm my_test python -c "import theano"
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 94, in init_dev
    **args)
  File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
GpuArrayException: Could not load "libcuda.so": /usr/lib/x86_64-linux-gnu/libcuda.so: file too short
```

### 2. Steps to reproduce the issue
Copy the following Dockerfile:
```dockerfile
FROM nvidia/cuda:8.0-cudnn5-devel

RUN apt-get update && apt-get -y -o Dpkg::Options::="--force-confmiss" install --reinstall \
    build-essential \
    cmake \
    g++ \
    git \
    python-dev \
    python-pip \
    x264 > /dev/null

RUN pip install --upgrade pip

# Install libgpuarray (Theano requirement)
RUN pip install Cython numpy
RUN cd /opt/ && \
    git clone --branch v0.7.0 https://github.com/Theano/libgpuarray.git && \
    cd libgpuarray/ && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && make -j$(nproc) install && \
    cd .. && python setup.py build && python setup.py install && \
    ldconfig && \
    pip install theano==1.0.0

ENV THEANO_FLAGS=floatX=float32,device=cuda
```
Build it:
```bash
docker build -t my_test .
```
Run it with nvidia container runtime:
```bash
docker run --runtime=nvidia --rm my_test python -c "import theano"
```

If I change to old nvidia-docker version, it works:
```bash
sudo apt-get remove --purge nvidia-docker2  # I'm using the official PPA in the README for Ubuntu
sudo apt-get install -y nvidia-docker
nvidia-docker run --rm my_test python -c "import theano"  # succefully 
```

### 3. Information to attach

 - [ ] Driver information from `nvidia-smi -a`
```
Driver Version                      : 384.111

GPU 00000000:00:04.0
    Product Name                    : Tesla K80
```
 - [ ] Docker version from `docker version`
```
Server:
 Engine:
  Version:	17.12.0-ce
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```
 - [ ] Docker command, image and tag used (already in issue description)

**Comment by flx42** [comment]
Works for me with v2.
Please share the output of
```
docker run --runtime=nvidia --rm my_test sh -c 'apt-get update -qq && apt-get install -yqq file && grep /usr/lib/x86_64-linux-gnu /proc/self/mounts && file /usr/lib/x86_64-linux-gnu/libcuda.so && file $(readlink --canonicalize /usr/lib/x86_64-linux-gnu/libcuda.so)'
```

**Comment by marco-lavagnino** [comment]
This is the requested output:
```
overlay /usr/lib/x86_64-linux-gnu overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/KBHXTP4VVXJZJWNERWQQS5U7GG:/var/lib/docker/overlay2/l/XIHVF32A7T5KES5PE7FXUTCOAB:/var/lib/docker/overlay2/l/MPAH3VEMEVCPTL4QW7ALHNDDC3:/var/lib/docker/overlay2/l/CYGGTTJEVTG3OCOIZPWE3I5NZN:/var/lib/docker/overlay2/l/FEZS6NTX2RD2LDWMA7N65VZJKF:/var/lib/docker/overlay2/l/SIBAKBF4ZYTCUJ6AKJZ4JITFXG:/var/lib/docker/overlay2/l/XDCNCCF5PQ3UCYP5TKKSIJW5L7:/var/lib/docker/overlay2/l/AG4UYQQVK43SY2HJTKFSN6WTVN:/var/lib/docker/overlay2/l/2KBXR7GDHWMQ4XVKJULCIIKOCP:/var/lib/docker/overlay2/l/XB5GLHMD5IDZIIBXWQGD7DZCOG:/var/lib/docker/overlay2/l/4VJ7DU7DDUMCDZVJFV5DFCWP6V:/var/lib/docker/overlay2/l/WU2CRSVDBNOBBV4ETKKLOKY6PL:/var/lib/docker/overlay2/l/YZFALA3EPDFMGVYEBDZFTRX7YD:/var/lib/docker/overlay2/l/YEEIBXOVNIRK2NVEK7SINFGPKO:/var/lib/docker/overlay2/l/UO22LFISEUYXYP6MZUXL6QWIDJ:/var/lib/docker/overlay2/l/UGSEZ5YTEL77664HB2KSEZG3P7,upperdir=/var/lib/docker/overlay2/3048c12ae3b82b3cd2a9f5c3e4b33fbbfc0e3101467507afb743004403d8ca1d/diff,workdir=/var/lib/docker/overlay2/3048c12ae3b82b3cd2a9f5c3e4b33fbbfc0e3101467507afb743004403d8ca1d/work 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libcuda.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libnvidia-fatbinaryloader.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/dev/sda1 /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.384.111 ext4 ro,nosuid,nodev,relatime,data=ordered 0 0
/usr/lib/x86_64-linux-gnu/libcuda.so: symbolic link to libcuda.so.384.111
/usr/lib/x86_64-linux-gnu/libcuda.so.384.111: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```

**Comment by flx42** [comment]
Everything looks normal.
Are the CUDA samples working on the host system?

**Comment by marco-lavagnino** [comment]
I rebuilt the Theano image without any cached layers and now it works without raising that exception. I don't know what happened, but now I can't replicate the problem I had yesterday.

I'm clossing this issue since there's no way to know what was wrong with that image.
