### ISSUE TITLE
RHEL7 transaction check error: file /etc/docker/daemon.json

### ISSUE THREAD

**Issue by Ouwen** [NVIDIA/nvidia-docker#640]
In trying to install nvidia-docker2 I run into the following error.

```
yum install nvidia-docker2-2.0.2-1.docker1.12.6
Loaded plugins: product-id, rhnplugin, search-disabled-repos, versionlock
This system is receiving updates from RHN Classic or Red Hat Satellite.
Resolving Dependencies
--> Running transaction check
---> Package nvidia-docker2.noarch 0:2.0.2-1.docker1.12.6 will be installed
--> Processing Dependency: nvidia-container-runtime = 1.1.1-1.docker1.12.6 for package: nvidia-docker2-2.0.2-1.docker1.12.6.noarch
--> Running transaction check
---> Package nvidia-container-runtime.x86_64 0:1.1.1-1.docker1.12.6 will be installed
--> Processing Dependency: libnvidia-container-tools < 2.0.0 for package: nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64
--> Processing Dependency: libnvidia-container-tools >= 0.1.0 for package: nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64
--> Running transaction check
---> Package libnvidia-container-tools.x86_64 0:1.0.0-0.1.alpha.3 will be installed
--> Processing Dependency: libnvidia-container1(x86-64) >= 1.0.0-0.1.alpha.3 for package: libnvidia-container-tools-1.0.0-0.1.alpha.3.x86_64
--> Processing Dependency: libnvidia-container.so.1(NVC_1.0)(64bit) for package: libnvidia-container-tools-1.0.0-0.1.alpha.3.x86_64
--> Processing Dependency: libnvidia-container.so.1()(64bit) for package: libnvidia-container-tools-1.0.0-0.1.alpha.3.x86_64
--> Running transaction check
---> Package libnvidia-container1.x86_64 0:1.0.0-0.1.alpha.3 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

====================================================================================================================================================================================================
 Package                                              Arch                              Version                                           Repository                                           Size
====================================================================================================================================================================================================
Installing:
 nvidia-docker2                                       noarch                            2.0.2-1.docker1.12.6                              nvidia-docker                                       4.6 k
Installing for dependencies:
 libnvidia-container-tools                            x86_64                            1.0.0-0.1.alpha.3                                 libnvidia-container                                  31 k
 libnvidia-container1                                 x86_64                            1.0.0-0.1.alpha.3                                 libnvidia-container                                  69 k
 nvidia-container-runtime                             x86_64                            1.1.1-1.docker1.12.6                              nvidia-container-runtime                            2.2 M

Transaction Summary
====================================================================================================================================================================================================
Install  1 Package (+3 Dependent packages)

Total size: 2.3 M
Installed size: 7.6 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test


Transaction check error:
  file /etc/docker/daemon.json from install of nvidia-docker2-2.0.2-1.docker1.12.6.noarch conflicts with file from package docker-2:1.12.6-71.git3e8e77d.el7.x86_64

Error Summary
-------------
```

What is the best way to install these drivers?

**Comment by flx42** [comment]
Yes, I already reported that to @jeremyeder, not sure if that will be fixed. Their version of docker installs an empty `daemon.json`.
But stay tuned, I'm going to publish new packages soon and it will be easier to configure GPU support for this version of docker (which is Red Hat's fork of Docker).

**Comment by Ouwen** [comment]
Thanks @flx42, i'm looking forward to it! 😄

**Comment by jeremyeder** [comment]
@zvonkok fyi

**Comment by zvonkok** [comment]
@Ouwen you don't need to install nvidia-docker2 package, for the time beeing,  just install nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64. Red Hats fork of Docker has all patches to run the nvida-container-runtime-hook natively. Create the following file: `  /usr/libexec/oci/hooks.d/oci-nvidia-hook` with content:
```
#!/bin/bash

if [ $1 == "prestart" ]; then
	PATH=/usr/bin /usr/bin/nvidia-container-runtime-hook -prestart
fi
```
This will activate the hook for the Red Hat Docker runtime, no custom runtime needed. 
Edit the file `/etc/nvidia-container-runtime/config.toml` and enable the debug
statement, this way you can easily see if the hooks gets called.
`tail -f /var/log/nvidia-container-runtime-hook.log`

The new packaging will remove unneeded parts in the Red Hat case because of the features
it provides.

**Comment by Ouwen** [comment]
@zvonkok Thanks for the help your suggestions worked.
Here are the commands I ran:

```bash
# installed nvidia-container-runtime
yum install nvidia-container-runtime-1.1.1-1.docker1.12.6.x86_64

# copied your script
touch /usr/libexec/oci/hooks.d/oci-nvidia-hook
vim /usr/libexec/oci/hooks.d/oci-nvidia-hook

# enabled debug mode
vim /etc/nvidia-container-runtime/config.toml

# ran docker natively
docker run -it nvidia/cuda nvidia-smi
```

This gives me an error
```sh
panic: standard_init_linux.go:178: exec user process caused "permission denied" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "permission denied"

goroutine 1 [running, locked to thread]:
github.com/urfave/cli.HandleAction.func1(0xc4200b57a0)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x23f
panic(0x6f0cc0, 0xc42013f3b0)
	/usr/lib/golang/src/runtime/panic.go:489 +0x2cf
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc4200b5208, 0xc42000e0a8, 0xc4200b52a8)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xc1
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc420056870, 0xaa88e0, 0xc42013f3b0)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x353
main.glob..func8(0xc42008e780, 0x0, 0x0)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/main_unix.go:26 +0x66
reflect.Value.call(0x6d9be0, 0x750350, 0x13, 0x73b942, 0x4, 0xc4200b5760, 0x1, 0x1, 0xc4200b56f0, 0x731420, ...)
	/usr/lib/golang/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x6d9be0, 0x750350, 0x13, 0xc4200b5760, 0x1, 0x1, 0x665b36, 0x73bace, 0x4)
	/usr/lib/golang/src/reflect/value.go:302 +0xa4
github.com/urfave/cli.HandleAction(0x6d9be0, 0x750350, 0xc42008e780, 0x0, 0x0)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x18f
github.com/urfave/cli.Command.Run(0x73baee, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x74d391, 0x51, 0x0, ...)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xac8
github.com/urfave/cli.(*App).Run(0xc4200d8000, 0xc42000c140, 0x2, 0x2, 0x0, 0x0)
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0x5d6
main.main()
	/builddir/build/BUILD/docker-3e8e77dcb88db0530c839b249bea7d75f9cd01d7/runc-c5d311627d39439c5b1cc35c67a51c9c6ccda648/main.go:137 +0xbd2
```

Interestingly, running the following has no problem
```
docker run -it nvidia/cuda sh -c "nvidia-smi"
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:13:00.0 Off |                    0 |
| N/A   25C    P0    24W / 250W |      0MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by 3XX0** [comment]
@Ouwen what's your OS distribution/version and how did you install the drivers?

**Comment by flx42** [comment]
You probably need to `chmod +x` the script.

**Comment by Ouwen** [comment]
@flx42 I did do a `chmod +x`, it was giving a different error without it. I should have documented that.

@3XX0 

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:	7.4
Codename:	Maipo
```

**Comment by zvonkok** [comment]
@Ouwen is SELinux enabled? On the host do a `$ getenforce` if it says `Enforcing` do the following
to check the SELinux labels in the container.
`docker run -it nvidia/cuda  /bin/bash` and in the container do
`ls -Z /dev/nvidia*`
If it says `permission denied` you have to change the labels on the host or disable SELinux. 

To  have the correct label please do `ls -Z /dev/` in the container and look for the label 
either it is `svirt_sandbox_file_t` or in updated RHEL 7.4 it is `container_file_t`.

After that you can do a `chcon -t container_file_t /dev/nvidia*` or `chcon -t svirt_sandbox_file_t /dev/nvidia*`

If you're using the NVIDIA drivers on the host, e.g. for Xorg and in the container, the better solution
here would be then to disable SELinux, the relabeling might brake stuff on the host.

**Comment by 3XX0** [comment]
@Ouwen how did you install the driver?

**Comment by Ouwen** [comment]
@zvonkok seems like SELinux is fine it is set to `Permissive` 
```
~/tmp $ docker run -it nvidia/cuda /bin/bash
root@58a0602ad776:/# ls -Z /dev/nvidia*
             system_u:object_r:device_t:s0 /dev/nvidia-uvm        system_u:object_r:xserver_misc_device_t:s0 /dev/nvidia0
             system_u:object_r:device_t:s0 /dev/nvidia-uvm-tools  system_u:object_r:xserver_misc_device_t:s0 /dev/nvidiactl
root@58a0602ad776:/# nvidia-smi
Thu Mar  1 05:59:18 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:13:00.0 Off |                    0 |
| N/A   24C    P0    24W / 250W |      0MiB / 16276MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

@3XX0 
I really wish I could say how the drivers were installed. Unfortunately, this VM had them preinstalled and is on an airgap.

I'm currently fine with having access to the drivers through bash. It is strange though that I run into the permission error if I try `docker run -it nvidia/cuda nvidia-smi`

Let me know if there is any other information I can get for you guys to make this a more reproducible bug. Might just be my specific machine.

**Comment by 3XX0** [comment]
try `nvidia-container-cli -k list | restorecon -v -f -` as root, see if it fixes the problem.

**Comment by 3XX0** [comment]
Closing as dup of #627

**Comment by flx42** [comment]
@zvonkok is the empty `daemon.json` going to be removed in a future release of the `docker` package on RH?

**Comment by zvonkok** [comment]
@flx42 Third-party tool should have to handle the existence of this file.  Users/admin are allowed to set configuration data in this file to allow customization of the docker daemon.

**Comment by flx42** [comment]
I know that, but creating an empty file is still surprising and creates a rpm-level conflict. Unfortunately, I don't see a good solution to customize the docker daemon in a robust way.

The two solutions: systemd drop-in file and daemon.json might conflict with previous settings. 
We decided to go for `daemon.json` since it seemed more likely that sysadmins would customize the systemd file first. But if `daemon.json` exists, it would be extremely painful to manually merge JSON files at install time, and to remove it at uninstall time.

**Comment by zvonkok** [comment]
@jeremyeder, @flx42 Is there any need to include the `daemon.json` file in the RHEL case? We only need the hook and the `daemon.json` file comes with the `nvidia-docker2` package, which registers the runtime we also not need. 

Are you thinking of adding more customizations to docker, besides adding the default runtime?

Do you want that all distributions install the `nvidia-docker2` package, unified install for all?

- Then what about making the `nvidia-docker2` package a virtual/transient package without the `daemon.json` file and just pulls as a dependency the hook in the RHEL/Centos/Fedora case?
- Or leave it as is, the conflicting `daemon.json` file could be a warning sign for people installing the `nvidia-docker2` package, that in the RHEL case, they do not need this package, only the hook?

[FYI] [jq](https://stedolan.github.io/jq/) (command-line JSON processor) is written in portable C, and it has zero runtime dependencies

**Comment by duckunix** [comment]
#627  is about SELinux permissions and this issue is about rpm packaging issues, so I feel that this should be still open.

**Comment by flx42** [comment]
> Do you want that all distributions install the nvidia-docker2 package, unified install for all?

No, but they should have the same experience, if they want to.

> Or leave it as is, the conflicting daemon.json file could be a warning sign for people installing the nvidia-docker2 package, that in the RHEL case, they do not need this package, only the hook?

You still haven't told me why your package ships an empty file :)

**Comment by yee379** [comment]
i think i'm having the same issue as you @Ouwen. did you ever find a fix for the permissions denied issue? i also have selinux to permissive.

**Comment by dwgoon** [comment]
I also have the same issue. Is there any solution for it??
