### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer when i use nvidia-docker to run mxnet

### ISSUE THREAD

**Issue by qinzhenyi1314** [NVIDIA/nvidia-docker#955]
i have a GeForce GTX 980 Ti to run mxnet ，when i enlarge batch_size have a error ConnectionResetError: [Errno 104] Connection reset by peer 

my machine
|   0  GeForce GTX 980 Ti  Off  | 00000000:01:00.0 Off |                  N/A |
| 33%   37C    P0    46W / 280W |      0MiB /  6082MiB |      0%      Default |

batch_size 128 everyting is ok

batch_size 256 The following error occurred

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mxnet/python/mxnet/gluon/data/dataloader.py", line 175, in fetcher_loop
    idx, batch = data_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/opt/mxnet/python/mxnet/gluon/data/dataloader.py", line 56, in rebuild_ndarray
    fd = fd.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by RenaudWasTaken** [comment]
Hello!

Looks like an MXnet error you should open an issue there!
